<?php

namespace Database\Seeders\Admin;

use App\Models\Coupon;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CouponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coupons = [
            [
                'code' => 'WELCOME10',
                'name' => 'Welcome Discount',
                'description' => 'Welcome discount for new customers',
                'type' => 'percentage',
                'value' => 10.00,
                'usage_limit' => 100,
                'usage_count' => 25,
                'user_limit' => 1,
                'min_purchase_amount' => 50.00,
                'min_items' => 1,
                'starts_at' => Carbon::now()->subDays(30),
                'expires_at' => Carbon::now()->addDays(30),
                'status' => true,
                'first_order_only' => true,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'SAVE20',
                'name' => 'Save 20%',
                'description' => 'General 20% discount on all products',
                'type' => 'percentage',
                'value' => 20.00,
                'usage_limit' => 200,
                'usage_count' => 45,
                'user_limit' => null,
                'min_purchase_amount' => 100.00,
                'min_items' => 2,
                'starts_at' => Carbon::now()->subDays(15),
                'expires_at' => Carbon::now()->addDays(45),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'FIXED50',
                'name' => '$50 Off',
                'description' => 'Get $50 off on your purchase',
                'type' => 'fixed_amount',
                'value' => 50.00,
                'usage_limit' => 50,
                'usage_count' => 12,
                'user_limit' => 2,
                'min_purchase_amount' => 200.00,
                'min_items' => 3,
                'starts_at' => Carbon::now()->subDays(10),
                'expires_at' => Carbon::now()->addDays(20),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'FREESHIP',
                'name' => 'Free Shipping',
                'description' => 'Get free shipping on your order',
                'type' => 'fixed_amount',
                'value' => 0.00,
                'usage_limit' => null,
                'usage_count' => 80,
                'user_limit' => null,
                'min_purchase_amount' => 75.00,
                'min_items' => 1,
                'starts_at' => Carbon::now()->subDays(5),
                'expires_at' => Carbon::now()->addDays(60),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => true,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'SUMMER25',
                'name' => 'Summer Sale',
                'description' => 'Special summer sale discount',
                'type' => 'percentage',
                'value' => 25.00,
                'usage_limit' => 150,
                'usage_count' => 90,
                'user_limit' => 1,
                'min_purchase_amount' => null,
                'min_items' => null,
                'starts_at' => Carbon::now()->subMonths(1),
                'expires_at' => Carbon::now()->addDays(15),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'VIP100',
                'name' => 'VIP Exclusive',
                'description' => 'VIP customer exclusive discount',
                'type' => 'fixed_amount',
                'value' => 100.00,
                'usage_limit' => 20,
                'usage_count' => 5,
                'user_limit' => 1,
                'min_purchase_amount' => 500.00,
                'min_items' => null,
                'starts_at' => Carbon::now(),
                'expires_at' => Carbon::now()->addMonths(3),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => true,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => json_encode([1, 2, 3]), // VIP user IDs
            ],
            [
                'code' => 'EXPIRED20',
                'name' => 'Expired Coupon',
                'description' => 'This coupon has expired',
                'type' => 'percentage',
                'value' => 20.00,
                'usage_limit' => 50,
                'usage_count' => 30,
                'user_limit' => null,
                'min_purchase_amount' => null,
                'min_items' => null,
                'starts_at' => Carbon::now()->subMonths(2),
                'expires_at' => Carbon::now()->subDays(10),
                'status' => false,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'INACTIVE15',
                'name' => 'Inactive Coupon',
                'description' => 'This coupon is inactive',
                'type' => 'percentage',
                'value' => 15.00,
                'usage_limit' => 100,
                'usage_count' => 0,
                'user_limit' => null,
                'min_purchase_amount' => 30.00,
                'min_items' => 1,
                'starts_at' => Carbon::now()->addDays(5),
                'expires_at' => Carbon::now()->addMonths(1),
                'status' => false,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'PRODUCT10',
                'name' => 'Product Specific',
                'description' => 'Discount on specific products only',
                'type' => 'percentage',
                'value' => 10.00,
                'usage_limit' => null,
                'usage_count' => 15,
                'user_limit' => null,
                'min_purchase_amount' => null,
                'min_items' => null,
                'starts_at' => Carbon::now()->subDays(20),
                'expires_at' => Carbon::now()->addDays(40),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => json_encode([1, 2, 3]), // Product IDs
                'included_categories' => null,
                'included_users' => null,
            ],
            [
                'code' => 'CATEGORY30',
                'name' => 'Category Discount',
                'description' => '30% off on specific categories',
                'type' => 'percentage',
                'value' => 30.00,
                'usage_limit' => 80,
                'usage_count' => 25,
                'user_limit' => null,
                'min_purchase_amount' => 80.00,
                'min_items' => 2,
                'starts_at' => Carbon::now()->subDays(7),
                'expires_at' => Carbon::now()->addDays(30),
                'status' => true,
                'first_order_only' => false,
                'free_shipping' => false,
                'included_products' => null,
                'included_categories' => json_encode([1, 2]), // Category IDs
                'included_users' => null,
            ],
        ];

        foreach ($coupons as $coupon) {
            Coupon::create($coupon);
        }

        $this->command->info('10 coupons seeded successfully!');
    }
}
